#!bin/bash

# * MONITORAR PASTEBIN E OBTER O LINK DAS POSTAGENS COM ALGUM CONTEUDO ESPECIFICO *

# ACESSAR O PASTEBIN

#   EXTRAIR OS LINKS DAS NOVAS POSTAGENS

#   ACESSAR CADA UM DOS LINKS E OBTER CONTEUDO

#     FILTRAR O CONTEUDO QUE EU QUERO

#     EXIBIR O LINK (OU NAO) / SALVAR O LINK

